const data = [
    {
        "title": "FIFA 22",
        "image": "https://s3.gaming-cdn.com/images/products/9071/271x377/fifa-22-pc-juego-origin-cover.jpg",
        "price": "45.98",
        "platform": "Origin",
        "tags": [
            "Cooperativo en línea",
            "Cooperativa local",
            "Cooperación",
            "JcJ online",
            "MMO",
            "Multijugador",
            "Simulación",
            "Un solo jugador",
            "Deporte",
            "Sports",
            "Soccer",
            "Immersive Sim",
            "Football",
            "PvP",
            "Competitive",
            "eSports",
            "Controller",
            "Physics",
            "Team-Based",
            "Simulation",
            "Realistic",
            "Family Friendly",
            "Cinematic",
            "Local Multiplayer",
            
        ],
        "rating": "51"
    },
    {
        "title": "Far Cry 6 (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/7080/271x377/far-cry-6-pc-juego-ubisoft-connect-europe-cover.jpg",
        "price": "50.99",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "FPS",
            "Open World",
            "Narrative",
            "Shooter"
        ],
        "rating": "63"
    },
    {
        "title": "Battlefield 2042",
        "image": "https://s1.gaming-cdn.com/images/products/6690/271x377/battlefield-2042-pc-juego-origin-cover.jpg",
        "price": "45.99",
        "platform": "Origin",
        "tags": [
            "Acción",
            "Aventura",
            "Wargame",
            "FPS",
            "JcJ online",
            "Cooperativo en línea",
            "Multijugador",
            "Cooperación",
            "Casual",
            "Shooter",
            "Action",
            "First-Person",
            "Military",
            "Team-Based",
            "Futuristic",
            "PvP",
            "Vehicular Combat",
            "Combat",
            "Modern",
            "Destruction",
            "Physics",
            "Cinematic",
            "Adventure",
            "Hero Shooter",
            "Action RPG",
            
        ],
        "rating": "?"
    },
    {
        "title": "New World Deluxe",
        "image": "https://s1.gaming-cdn.com/images/products/9771/271x377/new-world-deluxe-deluxe-edition-pc-juego-steam-cover.jpg",
        "price": "35.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperativo en línea",
            "Cooperación",
            "JcJ online",
            "MMO",
            "Multijugador",
            "RPG",
            "Massively Multiplayer",
            "MMORPG",
            "Open World",
            "Adventure",
            "RPG",
            "Action",
            "PvP",
            "PvE",
            "Fantasy",
            "Character Customization",
            "Third Person",
            "Crafting",
            "Sandbox",
            "Violent",
            "Open World Survival Craft",
            "Walking Simulator",
            "Souls-like",
            "Sexual Content",
            
        ],
        "rating": "90"
    },
    {
        "title": "Sea of Thieves (PC / Xbox ONE)",
        "image": "https://s2.gaming-cdn.com/images/products/967/271x377/juego-xbox-play-anywhere-sea-of-thieves-pc-xbox-one-cover.jpg",
        "price": "16.50",
        "platform": "Microsoft Store",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "Multijugador",
            "Pirates",
            "Open World",
            "Pirates",
            "Sailing",
            "PvP",
            "First-Person",
            "Funny",
            "PvE",
            "Online Co-Op",
            "Massively Multiplayer",
            "Masterpiece",
            
        ],
        "rating": "83"
    },
    {
        "title": "Horizon Zero Dawn Complete Edition",
        "image": "https://s2.gaming-cdn.com/images/products/6202/271x377/juego-steam-horizon-zero-dawn-complete-edition-cover.jpg",
        "price": "14.98",
        "platform": "Steam",
        "tags": [
            "Oferta de la semana",
            "Entrenamiento",
            "RPG",
            "Open World",
            "Female Protagonist",
            "Masterpiece",
            "Post-apocalyptic",
            "Story Rich",
            "Robots",
            "Sci-fi",
            "Singleplayer",
            "Third Person",
            "Beautiful",
            "Atmospheric",
            "Exploration",
            "Action RPG",
            "Hunting",
            "Archery",
            "Fantasy",
            
        ],
        "rating": "84"
    },
    {
        "title": "Forza Horizon 5: Premium Edition (PC / Xbox ONE / Xbox Series X|S)",
        "image": "https://s1.gaming-cdn.com/images/products/9567/271x377/forza-horizon-5-premium-edition-pc-xbox-one-xbox-series-xs-premium-edition-pc-xbox-one-xbox-serie-x-s-juego-microsoft-store-cover.jpg",
        "price": "82.99",
        "platform": "Microsoft Store",
        "tags": [
            "Carreras",
            "Aventura",
            "Simulación",
            "Arcade",
            "Deporte",
            "Cooperación",
            "Cooperativo en línea",
            "Acción",
            "Un solo jugador",
            "JcJ online",
            "Multijugador multiplataforma",
            "Multijugador",
            "Racing",
            "Open World",
            "Automobile Sim",
            "Exploration",
            "Realistic",
            "Driving",
            "First-Person",
            "Atmospheric",
            "PvP",
            
        ],
        "rating": "?"
    },
    {
        "title": "New World",
        "image": "https://s2.gaming-cdn.com/images/products/5932/271x377/new-world-pc-juego-steam-cover.jpg",
        "price": "31.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "Multijugador",
            "RPG",
            "Massively Multiplayer",
            "Violent",
            "Fantasy",
            "Open World",
            "PvP",
            "Third Person",
            "MMORPG",
            "PvE",
            "Character Customization",
            
        ],
        "rating": "90"
    },
    {
        "title": "Cyberpunk 2077",
        "image": "https://s1.gaming-cdn.com/images/products/840/271x377/juego-gog-com-cyberpunk-2077-cover.jpg",
        "price": "19.99",
        "platform": "GOG.com",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "FPS",
            "RPG",
            "Un solo jugador",
            "Cyberpunk",
            "Open World",
            "RPG",
            "Sci-fi",
            "Futuristic",
            "First-Person",
            "Atmospheric",
            "Nudity",
            "Exploration",
            "Story Rich",
            "Mature",
            "Violent",
            "Action RPG",
            "Immersive Sim",
            "Character Customization",
            
        ],
        "rating": "75"
    },
    {
        "title": "Far Cry 5 (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/1842/271x377/juego-uplay-far-cry-5-cover.jpg",
        "price": "11.49",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "FPS",
            "Multijugador",
            "Open World",
            "Shooter",
            "First-Person",
            "Singleplayer",
            "Survival",
            "America",
            "Stealth",
            "Story Rich",
            "Hunting",
            "Exploration",
            "Atmospheric",
            "Character Customization",
            "Sexual Content",
            "Nudity",
            
        ],
        "rating": "76"
    },
    {
        "title": "Hot Wheels Unleashed",
        "image": "https://s1.gaming-cdn.com/images/products/8223/271x377/hot-wheels-unleashed-pc-juego-steam-cover.jpg",
        "price": "24.49",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Carreras",
            "Arcade",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Racing",
            "Split Screen",
            "Third Person",
            "PvP",
            "Local Multiplayer",
            "Hentai",
            
        ],
        "rating": "95"
    },
    {
        "title": "Los Sims 4 Vida en el Pueblo",
        "image": "https://s2.gaming-cdn.com/images/products/8968/271x377/juego-origin-los-sims-4-vida-en-el-pueblo-cover.jpg",
        "price": "24.90",
        "platform": "Origin",
        "tags": [
            "Simulación",
            "Building",
            "Single Player",
            "Casual",
            "Character Customization",
            "Sandbox",
            "Moddable",
            "Family Friendly",
            "Romance",
            
        ],
        "rating": ""
    },
    {
        "title": "Overwatch",
        "image": "https://s1.gaming-cdn.com/images/products/2208/271x377/juego-battle-net-overwatch-cover.jpg",
        "price": "11.19",
        "platform": "Battle.net",
        "tags": [
            "Acción",
            "FPS",
            "MMO"
        ],
        "rating": "87"
    },
    {
        "title": "No Man's Sky",
        "image": "https://s1.gaming-cdn.com/images/products/414/271x377/no-mans-sky-pc-juego-steam-cover.jpg",
        "price": "14.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Aventura",
            "Indies",
            "Acción",
            "Simulación",
            "FPS",
            "Un solo jugador",
            "JcJ online",
            "Cooperativo en línea",
            "Multijugador",
            "Cooperación",
            "Open World",
            "Open World Survival Craft",
            "Space",
            "Exploration",
            "Sci-fi",
            "Survival",
            "Procedural Generation",
            "First-Person",
            "Sandbox",
            "Atmospheric",
            "Crafting",
            "Space Sim",
            
        ],
        "rating": "78"
    },
    {
        "title": "Nickelodeon All-Star Brawl",
        "image": "https://s2.gaming-cdn.com/images/products/9757/271x377/nickelodeon-all-star-brawl-pc-juego-steam-cover.jpg",
        "price": "27.49",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Arcade",
            "Beat'em all",
            "JcJ online",
            "Multijugador",
            "Remote Play Together",
            "Un solo jugador",
            "2D Fighter",
            "Action",
            "Cartoon",
            "1990's",
            "eSports",
            "2D Platformer",
            "2D",
            "Cartoony",
            "Cats",
            "Comedy",
            "Family Friendly",
            "Dog",
            "Funny",
            "PvP",
            "Combat",
            "PvE",
            
        ],
        "rating": "?"
    },
    {
        "title": "Office 2019 Home and Student PC",
        "image": "https://s3.gaming-cdn.com/images/products/4997/271x377/juego-software-office-2019-home-and-student-pc-cover.jpg",
        "price": "14.90",
        "platform": "Microsoft Store",
        "tags": [
            "Otro"
        ],
        "rating": "74"
    },
    {
        "title": "Dark Souls 3 Deluxe Edition",
        "image": "https://s3.gaming-cdn.com/images/products/2060/271x377/juego-steam-dark-souls-3-deluxe-edition-cover.jpg",
        "price": "15.49",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperación",
            "RPG"
        ],
        "rating": "93"
    },
    {
        "title": "Red Dead Redemption 2 Standard Edition",
        "image": "https://s1.gaming-cdn.com/images/products/5679/271x377/juego-rockstar-red-dead-redemption-2-standard-edition-cover.jpg",
        "price": "33.49",
        "platform": "Rockstar",
        "tags": [
            "Acción",
            "Aventura",
            "Open World",
            "Cowboy",
            "Western",
            "Gore",
            "Historical",
            "Shooter",
            "Singleplayer",
            "Multiplayer",
            
        ],
        "rating": "82"
    },
    {
        "title": "Assassin’s Creed Valhalla (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/6147/271x377/juego-uplay-assassin%e2%80%99s-creed-valhalla-cover.jpg",
        "price": "32.99",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Open World",
            "Parkour",
            "Assassin",
            "Stealth",
            "Third Person",
            "Historical",
            "Singleplayer",
            "Story Rich",
            "Hunting",
            "Atmospheric",
            "Action-Adventure",
            "Sandbox",
            "Controller",
            "Casual",
            
        ],
        "rating": "70"
    },
    {
        "title": "Medieval Dynasty",
        "image": "https://s1.gaming-cdn.com/images/products/7590/271x377/medieval-dynasty-pc-juego-steam-cover.jpg",
        "price": "15.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "RPG",
            "Simulación",
            "Un solo jugador",
            "Survival",
            "Building",
            "Open World",
            "Medieval",
            "RPG",
            "Simulation",
            "Crafting",
            "City Builder",
            "Adventure",
            "Sandbox",
            "Colony Sim",
            "Realistic",
            "Action",
            "Resource Management",
            "Historical",
            "Exploration",
            "First-Person",
            
        ],
        "rating": "88"
    },
    {
        "title": "Days Gone",
        "image": "https://s3.gaming-cdn.com/images/products/6791/271x377/days-gone-pc-juego-steam-cover.jpg",
        "price": "23.49",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Open World",
            "Post-apocalyptic",
            "Singleplayer",
            "Action-Adventure",
            "Zombies",
            "Survival",
            "Third Person",
            "Survival Horror",
            "Motorbike",
            "Horror",
            "Cinematic",
            "Crafting",
            "Open World Survival Craft",
            "Third-Person Shooter",
            "Gore",
            "Violent",
            "Story Rich",
            
        ],
        "rating": "89"
    },
    {
        "title": "Assetto Corsa Ultimate Edition",
        "image": "https://s3.gaming-cdn.com/images/products/3098/271x377/juego-steam-assetto-corsa-ultimate-edition-cover.jpg",
        "price": "13.65",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Carreras",
            "Indies",
            "JcJ online",
            "Multijugador",
            "Simulación",
            "Un solo jugador",
            "Deporte",
            "VR",
            "Automobile Sim",
            "Driving",
            "Realistic",
            "Moddable",
            "Controller",
            "Physics",
            "Open World",
            "First-Person",
            "Replay Value",
            "3D Vision",
            "TrackIR",
            "Artificial Intelligence",
            
        ],
        "rating": "90"
    },
    {
        "title": "Tom Clancy's Ghost Recon: Breakpoint (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/4595/271x377/juego-uplay-tom-clancys-ghost-recon-breakpoint-cover.jpg",
        "price": "11.88",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "FPS",
            "Multijugador",
            "Estrategia",
            "Open World",
            "Shooter",
            "Tactical",
            "Stealth",
            "Third-Person Shooter",
            "Military",
            "Singleplayer",
            "Third Person",
            "Online Co-Op",
            "Sandbox",
            "Survival",
            "First-Person",
            "Atmospheric",
            "PvP",
            "Essentials",
            
        ],
        "rating": "64"
    },
    {
        "title": "Dark Souls Remastered",
        "image": "https://s1.gaming-cdn.com/images/products/2364/271x377/juego-steam-dark-souls-remastered-cover.jpg",
        "price": "15.56",
        "platform": "Steam",
        "tags": [
            "Acción",
            "RPG",
            "Aventura",
            "Un solo jugador",
            "Souls-like",
            "Education",
            "Dark Fantasy",
            "Action",
            "Dark",
            "Difficult",
            "Fantasy",
            "Atmospheric",
            "Action RPG",
            "Lore-Rich",
            "Replay Value",
            "Third Person",
            "Exploration",
            "Story Rich",
            "Character Customization",
            "Soundtrack",
            
        ],
        "rating": "88"
    },
    {
        "title": "Back 4 Blood Deluxe (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/8036/271x377/back-4-blood-deluxe-deluxe-edition-pc-juego-steam-europe-cover.jpg",
        "price": "78.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperativo en línea",
            "FPS",
            "Cooperación",
            "Aventura",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Action",
            "Zombies",
            "Shooter",
            "First-Person",
            "Gore",
            "Blood",
            "Violent",
            "PvP",
            "Horror",
            "Survival",
            "Survival Horror",
            "PvE",
            "Replay Value",
            "Roguelite",
            
        ],
        "rating": "?"
    },
    {
        "title": "Office Professional Plus 2019 PC (1 User)",
        "image": "https://s3.gaming-cdn.com/images/products/3212/271x377/juego-software-office-professional-plus-2019-pc-1-user-cover.jpg",
        "price": "22.99",
        "platform": "Microsoft Store",
        "tags": [
            "Otro",
            "Office",
            "Software",
            "Windows"
        ],
        "rating": "74"
    },
    {
        "title": "Farming Simulator 22",
        "image": "https://s1.gaming-cdn.com/images/products/8676/271x377/farming-simulator-22-pc-mac-juego-steam-cover.jpg",
        "price": "29.99",
        "platform": "Steam",
        "tags": [
            "Simulación",
            "Cooperación",
            "Gestión",
            "Cooperativo en línea",
            "Un solo jugador",
            "Multijugador multiplataforma",
            "Multijugador",
            "Simulation",
            "Farming Sim",
            "Agriculture",
            "Moddable",
            "Sandbox",
            "Immersive Sim",
            "3D",
            "First-Person",
            "Character Customization",
            "Third Person",
            "Economy",
            "America",
            "Family Friendly",
            "Nature",
            "Open World",
            "Horses",
            
        ],
        "rating": "?"
    },
    {
        "title": "Football Manager 2022 (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/8021/271x377/football-manager-2022-pc-juego-steam-europe-cover.jpg",
        "price": "34.98",
        "platform": "Steam",
        "tags": [
            "Simulación",
            "Deporte",
            "Gestión",
            "Estrategia",
            "Un solo jugador",
            "Sports",
            "Real Time Tactics",
            "Soccer",
            "Simulation",
            "Football",
            "eSports",
            "Character Customization",
            "2D",
            "3D",
            "Text-Based",
            "Fantasy",
            
        ],
        "rating": "?"
    },
    {
        "title": "Grand Theft Auto Online: Megalodon Shark Cash Card",
        "image": "https://s1.gaming-cdn.com/images/products/1095/271x377/juego-rockstar-grand-theft-auto-online-megalodon-shark-cash-card-cover.jpg",
        "price": "32.99",
        "platform": "Rockstar",
        "tags": [],
        "rating": ""
    },
    {
        "title": "Gas Station Simulator",
        "image": "https://s2.gaming-cdn.com/images/products/9502/271x377/gas-station-simulator-pc-juego-steam-cover.jpg",
        "price": "13.49",
        "platform": "Steam",
        "tags": [
            "Indies",
            "Simulación",
            "Un solo jugador",
            "Simulation",
            "Indie",
            "Building",
            "Economy",
            "Realistic",
            "Base Building",
            "Open World",
            "Crafting",
            "First-Person",
            "Relaxing",
            "Casual",
            "Design & Illustration",
            "Funny",
            "Family Friendly",
            "Destruction",
            "Choices Matter",
            "Memes",
            "Education",
            
        ],
        "rating": "60"
    },
    {
        "title": "Bus Simulator 21",
        "image": "https://s1.gaming-cdn.com/images/products/9108/271x377/bus-simulator-21-pc-juego-steam-cover.jpg",
        "price": "26.49",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Simulación",
            "Cooperación",
            "Cooperativo en línea",
            "Gestión",
            "Un solo jugador",
            "Simulation",
            "Automobile Sim",
            "Immersive Sim",
            "3D",
            "Colorful",
            "Realistic",
            "First-Person",
            "Driving",
            "Third Person",
            "Family Friendly",
            "Modern",
            "Relaxing",
            "Character Customization",
            "Controller",
            "Open World",
            
        ],
        "rating": "64"
    },
    {
        "title": "Assetto Corsa Competizione",
        "image": "https://s1.gaming-cdn.com/images/products/3153/271x377/assetto-corsa-competizione-pc-juego-steam-cover.jpg",
        "price": "11.79",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Carreras",
            "Multijugador",
            "Simulación",
            "Deporte",
            "Driving",
            "VR",
            "Realistic",
            "Singleplayer",
            "eSports",
            
        ],
        "rating": "83"
    },
    {
        "title": "Orcs Must Die! 3",
        "image": "https://s1.gaming-cdn.com/images/products/9060/271x377/orcs-must-die-3-pc-juego-steam-cover.jpg",
        "price": "10.49",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperativo en línea",
            "Cooperación",
            "Indies",
            "Un solo jugador",
            "Estrategia",
            "Tower Defense",
            "Strategy",
            "Third-Person Shooter",
            "PvE",
            "Action",
            "3D",
            "Funny",
            "Third Person",
            "Adventure",
            "Fantasy",
            "Combat",
            "Stylized",
            "Physics",
            "Co-op Campaign",
            "Comedy",
            "Cartoony",
            
        ],
        "rating": "86"
    },
    {
        "title": "Los Sims 4: Escapada en la Nieve",
        "image": "https://s1.gaming-cdn.com/images/products/7761/271x377/juego-origin-los-sims-4-escapada-en-la-nieve-cover.jpg",
        "price": "14.99",
        "platform": "Origin",
        "tags": [
            "Simulación",
            "Casual"
        ],
        "rating": "91"
    },
    {
        "title": "Monster Hunter: World (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/2155/271x377/juego-steam-monster-hunter-world-cover.jpg",
        "price": "12.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperación",
            "RPG",
            "Aventura",
            "Un solo jugador",
            "Action",
            "Open World",
            "Third Person",
            "Character Customization",
            "Fantasy",
            "Difficult",
            "Action RPG",
            "Exploration",
            "Replay Value",
            "Atmospheric",
            "Hack and Slash",
            "JRPG",
            "Souls-like",
            "MMORPG",
            
        ],
        "rating": "87"
    },
    {
        "title": "Dying Light: Platinum Edition",
        "image": "https://s3.gaming-cdn.com/images/products/8918/271x377/juego-steam-dying-light-platinum-edition-cover.jpg",
        "price": "13.49",
        "platform": "Steam",
        "tags": [
            "Acción",
            "RPG",
            "Cooperativo en línea",
            "FPS",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Cooperación",
            "Zombies",
            "Survival Horror",
            "Horror",
            "Open World",
            "Parkour",
            "First-Person",
            "Open World Survival Craft",
            "Survival",
            "Action",
            "Gore",
            "PvE",
            "PvP",
            "Stealth",
            "Post-apocalyptic",
            "Story Rich",
            "Hack and Slash",
            "Action RPG",
            "RPG",
            
        ],
        "rating": "91"
    },
    {
        "title": "Back 4 Blood (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/7988/271x377/back-4-blood-pc-juego-steam-europe-cover.jpg",
        "price": "51.98",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperativo en línea",
            "FPS",
            "Cooperación",
            "Aventura",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Action",
            "Zombies",
            "Shooter",
            "First-Person",
            "Gore",
            "Blood",
            "Violent",
            "PvP",
            "Horror",
            "Survival",
            "Survival Horror",
            "PvE",
            "Replay Value",
            "Roguelite",
            
        ],
        "rating": "?"
    },
    {
        "title": "Tales Of Arise",
        "image": "https://s3.gaming-cdn.com/images/products/5870/271x377/tales-of-arise-pc-juego-steam-cover.jpg",
        "price": "41.19",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "RPG",
            "Anime",
            "JRPG",
            "Action RPG",
            "Third Person",
            "Fantasy",
            "Magic",
            "Combat",
            "Controller",
            "Singleplayer",
            
        ],
        "rating": "77"
    },
    {
        "title": "FIFA 20",
        "image": "https://s3.gaming-cdn.com/images/products/4502/271x377/juego-origin-fifa-20-cover.jpg",
        "price": "10.99",
        "platform": "Origin",
        "tags": [
            "Multijugador",
            "Simulación",
            "Deporte",
            "Singleplayer",
            "Soccer",
            "Football",
            "Essentials",
            
        ],
        "rating": "46"
    },
    {
        "title": "Deathloop",
        "image": "https://s2.gaming-cdn.com/images/products/9451/271x377/deathloop-pc-juego-steam-cover.jpg",
        "price": "41.19",
        "platform": "Steam",
        "tags": [
            "Acción",
            "FPS",
            "Aventura",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Action",
            "First-Person",
            "Shooter",
            "Stealth",
            "Immersive Sim",
            "Assassin",
            "Roguelite",
            "Time Manipulation",
            "Story Rich",
            "Tactical",
            "PvP",
            "Violent",
            "Gore",
            "Sexual Content",
            "Parkour",
            "Action-Adventure",
            
        ],
        "rating": "84"
    },
    {
        "title": "Planet Zoo",
        "image": "https://s1.gaming-cdn.com/images/products/4479/271x377/juego-steam-planet-zoo-cover.jpg",
        "price": "14.89",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Simulación",
            "Estrategia",
            "Gestión",
            "Un solo jugador",
            "Casual",
            "Simulation",
            "Building",
            "Sandbox",
            "Nature",
            "City Builder",
            "Economy",
            "Family Friendly",
            "Realistic",
            "Resource Management",
            "Cute",
            "Strategy",
            "Open World",
            "Relaxing",
            "Funny",
            "Horses",
            
        ],
        "rating": "88"
    },
    {
        "title": "NBA 2K22 (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/8997/271x377/nba-2k22-standard-edition-europe-only-pc-juego-steam-europe-cover.jpg",
        "price": "41.99",
        "platform": "Steam",
        "tags": [
            "Simulación",
            "Deporte",
            "Gestión",
            "Cooperación",
            "Cooperativa local",
            "Cooperativo en línea",
            "Un solo jugador",
            "JcJ online",
            "Remote Play Together",
            "Multijugador",
            "Sports",
            "Simulation",
            "Basketball",
            "Realistic",
            "eSports",
            "3D",
            "Team-Based",
            "Character Customization",
            "Controller",
            "Deckbuilding",
            "Trading",
            "4 Player Local",
            "Gambling",
            "Local Multiplayer",
            
        ],
        "rating": "32"
    },
    {
        "title": "Monster Hunter: World - Iceborne",
        "image": "https://s3.gaming-cdn.com/images/products/4622/271x377/juego-steam-monster-hunter-world-iceborne-cover.jpg",
        "price": "16.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "Multijugador",
            "RPG",
            "Hunting",
            "Open World",
            "Difficult",
            "Masterpiece",
            "Third Person",
            "Online Co-Op",
            "Singleplayer",
            
        ],
        "rating": "87"
    },
    {
        "title": "Life is Strange: True Colors",
        "image": "https://s2.gaming-cdn.com/images/products/8512/271x377/life-is-strange-true-colors-pc-juego-steam-cover.jpg",
        "price": "31.89",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Un solo jugador",
            "Choices Matter",
            "Female Protagonist",
            "Choose Your Own Adventure",
            "LGBTQ+",
            "Story Rich",
            "Multiple Endings",
            "Romance",
            "Third Person",
            "Atmospheric",
            "Emotional",
            "Action",
            "Drama",
            "Stylized",
            "Adventure",
            "Mystery",
            "Cinematic",
            "Mature",
            "Narrative",
            "Supernatural",
            
        ],
        "rating": "78"
    },
    {
        "title": "Resident Evil Village",
        "image": "https://s3.gaming-cdn.com/images/products/6329/271x377/juego-steam-resident-evil-village-cover.jpg",
        "price": "27.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "FPS",
            "Multijugador",
            "Survival Horror",
            "Horror",
            "First-Person",
            "Singleplayer",
            "Gore",
            "Violent",
            "Atmospheric",
            "Zombies",
            "Story Rich",
            "Dark",
            "Survival",
            "Psychological Horror",
            
        ],
        "rating": "86"
    },
    {
        "title": "Farming Simulator 19",
        "image": "https://s1.gaming-cdn.com/images/products/3066/271x377/juego-steam-farming-simulator-19-cover.jpg",
        "price": "12.33",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Aventura",
            "Cooperación",
            "Gestión",
            "Multijugador",
            "Simulación",
            "Estrategia",
            "Agriculture",
            "Realistic",
            "Singleplayer",
            "Open World",
            "Driving",
            "Moddable",
            "Resource Management",
            "Relaxing",
            "First-Person",
            "Online Co-Op",
            "Atmospheric",
            "Economy",
            "Family Friendly",
            "Casual",
            
        ],
        "rating": "85"
    },
    {
        "title": "The Witcher 3: Wild Hunt GOTY",
        "image": "https://s1.gaming-cdn.com/images/products/1497/271x377/juego-gog-com-the-witcher-3-wild-hunt-goty-cover.jpg",
        "price": "11.49",
        "platform": "GOG.com",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "RPG"
        ],
        "rating": "95"
    },
    {
        "title": "Satisfactory",
        "image": "https://s3.gaming-cdn.com/images/products/4229/271x377/juego-steam-satisfactory-cover.jpg",
        "price": "26.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Aventura",
            "Early Access",
            "Multijugador"
        ],
        "rating": "92"
    },
    {
        "title": "Tails of Iron",
        "image": "https://s1.gaming-cdn.com/images/products/9510/271x377/tails-of-iron-pc-juego-steam-cover.jpg",
        "price": "16.19",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Indies",
            "RPG",
            "Un solo jugador",
            "Action-Adventure",
            "Combat",
            "Souls-like",
            "Action RPG",
            "Adventure",
            "Difficult",
            "Narration",
            "Story Rich",
            "Action",
            "Fantasy",
            "2D",
            "Dark Fantasy",
            "Atmospheric",
            "Character Customization",
            "2.5D",
            "Medieval",
            "Swordplay",
            "Inventory Management",
            
        ],
        "rating": "90"
    },
    {
        "title": "The Elder Scrolls V: Skyrim Legendary Edition",
        "image": "https://s3.gaming-cdn.com/images/products/209/271x377/the-elder-scrolls-v-skyrim-legendary-edition-legendary-edition-pc-juego-steam-cover.jpg",
        "price": "11.25",
        "platform": "Steam",
        "tags": [
            "RPG"
        ],
        "rating": "93"
    },
    {
        "title": "Destiny 2: Beyond Light Deluxe Edition (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/7098/271x377/destiny-2-beyond-light-deluxe-edition-deluxe-edition-pc-juego-steam-europe-cover.jpg",
        "price": "36.69",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "FPS",
            "Un solo jugador",
            "JcJ online",
            "Cooperativo en línea",
            "Multijugador",
            "Cooperación",
            "Action",
            "Adventure",
            "MMORPG",
            "Looter Shooter",
            "Shooter",
            
        ],
        "rating": "73"
    },
    {
        "title": "Red Dead Redemption 2: Ultimate Edition",
        "image": "https://s2.gaming-cdn.com/images/products/5653/271x377/juego-rockstar-red-dead-redemption-2-ultimate-edition-cover.jpg",
        "price": "41.99",
        "platform": "Rockstar",
        "tags": [
            "Acción",
            "Aventura",
            "Open World",
            "Cowboy",
            "Western",
            "Gore",
            "Historical",
            "Shooter",
            "Singleplayer",
            "Multiplayer",
            
        ],
        "rating": "82"
    },
    {
        "title": "Age of Empires III: Definitive Edition",
        "image": "https://s3.gaming-cdn.com/images/products/6275/271x377/juego-steam-age-of-empires-iii-definitive-edition-cover.jpg",
        "price": "10.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "Multijugador",
            "Simulación",
            "Estrategia",
            "Wargame",
            "RTS",
            "3D",
            "Historical",
            "Military",
            "PvP",
            "Singleplayer",
            "Base Building",
            "Combat",
            "Resource Management",
            "Story Rich",
            "Level Editor",
            "Moddable",
            
        ],
        "rating": "85"
    },
    {
        "title": "Assassin's Creed Odyssey (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/2648/271x377/juego-uplay-assassins-creed-odyssey-cover.jpg",
        "price": "11.99",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura"
        ],
        "rating": "86"
    },
    {
        "title": "Forza Horizon 5 (PC / Xbox ONE / Xbox Series X|S)",
        "image": "https://s2.gaming-cdn.com/images/products/8701/271x377/forza-horizon-5-pc-xbox-one-xbox-series-xs-pc-xbox-one-xbox-serie-x-s-juego-microsoft-store-cover.jpg",
        "price": "48.99",
        "platform": "Microsoft Store",
        "tags": [
            "Acción",
            "Arcade",
            "Aventura",
            "Cooperativo en línea",
            "Cooperación",
            "Carreras",
            "JcJ online",
            "Multijugador",
            "Multijugador multiplataforma",
            "Simulación",
            "Un solo jugador",
            "Deporte",
            "Racing",
            "Automobile Sim",
            "Open World",
            "Exploration",
            "Realistic",
            "Driving",
            "First-Person",
            "Atmospheric",
            "PvP",
            
        ],
        "rating": "?"
    },
    {
        "title": "Age of Darkness: Final Stand (Early Access)",
        "image": "https://s2.gaming-cdn.com/images/products/9691/271x377/age-of-darkness-final-stand-early-access-pc-juego-steam-cover.jpg",
        "price": "16.00",
        "platform": "Steam",
        "tags": [
            "Estrategia",
            "Early Access",
            "Un solo jugador",
            "RTS",
            "Survival",
            "Dark Fantasy",
            "Base Building",
            "Resource Management",
            "Fantasy",
            "Strategy",
            "Building",
            "Stylized",
            "Atmospheric",
            "Combat",
            "3D",
            "Dark",
            "Medieval",
            "Tactical",
            "Early Access",
            "PvE",
            "Action RTS",
            "Colony Sim",
            
        ],
        "rating": "?"
    },
    {
        "title": "Far Cry 5 Gold Edition (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/2680/271x377/juego-uplay-far-cry-5-gold-edition-cover.jpg",
        "price": "16.49",
        "platform": "Ubisoft Connect",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "FPS",
            "Multijugador",
            "Open World",
            "Shooter",
            "First-Person",
            "Singleplayer",
            "America",
            "Survival",
            "Stealth",
            "Hunting",
            "Story Rich",
            "Exploration",
            "Atmospheric",
            "Character Customization",
            "Sexual Content",
            "Nudity",
            
        ],
        "rating": "76"
    },
    {
        "title": "Los Sims 4 Interiorismo - Pack de Contenido",
        "image": "https://s2.gaming-cdn.com/images/products/8872/271x377/juego-origin-los-sims-4-interiorismo-pack-de-contenido-cover.jpg",
        "price": "17.99",
        "platform": "Origin",
        "tags": [
            "Simulación",
            "Building",
            "Single Player",
            "Casual",
            "Character Customization",
            "Sandbox",
            "Moddable",
            "Family Friendly",
            "Romance",
            
        ],
        "rating": "90"
    },
    {
        "title": "Watch Dogs Legion (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/2540/271x377/juego-uplay-watch-dogs-legion-cover.jpg",
        "price": "20.99",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "Multijugador",
            "Open World",
            "Hacking",
            "Third Person",
            "Stealth",
            "Third-Person Shooter",
            "Singleplayer",
            "Atmospheric",
            "Shooter",
            "Parkour",
            "Sandbox",
            "Epic",
            "Dog",
            "Driving",
            "Beautiful",
            "Futuristic",
            
        ],
        "rating": "65"
    },
    {
        "title": "Total War: Warhammer II (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/2014/271x377/juego-steam-total-war-warhammer-ii-cover.jpg",
        "price": "12.68",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperación",
            "Multijugador",
            "Estrategia",
            "Wargame",
            "Fantasy",
            "Turn-Based Strategy",
            "RTS",
            "Grand Strategy",
            "Games Workshop",
            "Turn-Based",
            "Singleplayer",
            "Dark Fantasy",
            "Tactical",
            "Real Time Tactics",
            "Atmospheric",
            "Story Rich",
            "Dinosaurs",
            "Warhammer 40K",
            
        ],
        "rating": "86"
    },
    {
        "title": "Ranch Simulator",
        "image": "https://s1.gaming-cdn.com/images/products/8133/271x377/juego-steam-ranch-simulator-cover.jpg",
        "price": "12.49",
        "platform": "Steam",
        "tags": [
            "Simulación",
            "Early Access",
            "Cooperativo en línea",
            "Cooperación",
            "Indies",
            "Gestión",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Early Access",
            "Simulation",
            "Farming Sim",
            "Open World",
            "Realistic",
            "Farming",
            "Hunting",
            "Sandbox",
            "Nature",
            "Immersive Sim",
            "Economy",
            "First-Person",
            "Relaxing",
            "Driving",
            
        ],
        "rating": "78"
    },
    {
        "title": "NBA 2K22",
        "image": "https://s3.gaming-cdn.com/images/products/9446/271x377/nba-2k22-pc-juego-steam-cover.jpg",
        "price": "41.99",
        "platform": "Steam",
        "tags": [
            "Simulación",
            "Deporte",
            "Gestión",
            "Cooperación",
            "Cooperativa local",
            "Cooperativo en línea",
            "Un solo jugador",
            "JcJ online",
            "Remote Play Together",
            "Multijugador",
            "Sports",
            "Simulation",
            "Basketball",
            "Realistic",
            "eSports",
            "3D",
            "Team-Based",
            "Character Customization",
            "Controller",
            "Deckbuilding",
            "Trading",
            "4 Player Local",
            "Gambling",
            "Local Multiplayer",
            
        ],
        "rating": "32"
    },
    {
        "title": "Wreckfest",
        "image": "https://s1.gaming-cdn.com/images/products/582/271x377/juego-steam-wreckfest-cover.jpg",
        "price": "10.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Arcade",
            "Aventura",
            "Cooperación",
            "Carreras",
            "Indies",
            "Multijugador",
            "Simulación",
            "Deporte",
            "Destruction",
            "Driving",
            "Physics",
            "Singleplayer",
            "Realistic",
            "Funny",
            "Sandbox",
            "Masterpiece",
            "Third Person",
            "Open World",
            "Atmospheric",
            
        ],
        "rating": "87"
    },
    {
        "title": "Destiny 2: The Witch Queen Deluxe + Bungie 30th Anniversary Bundle",
        "image": "https://s3.gaming-cdn.com/images/products/9428/271x377/destiny-2-the-witch-queen-deluxe-bungie-30th-anniversary-bundle-bundle-pack-pc-juego-steam-cover.jpg",
        "price": "70.89",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Un solo jugador",
            "JcJ online",
            "Cooperativo en línea",
            "Multijugador",
            "Cooperación",
            "Action",
            "Adventure",
            
        ],
        "rating": "98"
    },
    {
        "title": "Doom Eternal (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/2669/271x377/juego-bethesda-doom-eternal-cover.jpg",
        "price": "11.19",
        "platform": "Bethesda",
        "tags": [
            "Acción",
            "Aventura",
            "FPS",
            "Multijugador",
            "Gore",
            "Violent",
            "Demons",
            "First-Person",
            "Singleplayer",
            "Masterpiece",
            "Fast-Paced",
            "Shooter",
            "Sci-fi",
            "Atmospheric",
            "Blood",
            "Post-apocalyptic",
            "Story Rich",
            "Horror",
            "Mature",
            "Essentials",
            
        ],
        "rating": "85"
    },
    {
        "title": "Euro Truck Simulator 2 Complete Edition",
        "image": "https://s1.gaming-cdn.com/images/products/4425/271x377/juego-steam-euro-truck-simulator-2-complete-edition-cover.jpg",
        "price": "24.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Carreras",
            "Gestión",
            "Indies",
            "RPG",
            "Simulación",
            "Driving",
            "Open World",
            "Realistic",
            "Relaxing",
            "Singleplayer",
            "Moddable",
            "Exploration",
            "First-Person",
            "Economy",
            "Atmospheric",
            "Casual",
            "TrackIR",
            "Sandbox",
            
        ],
        "rating": "91"
    },
    {
        "title": "Borderlands 3 (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/6667/271x377/juego-steam-borderlands-3-cover.jpg",
        "price": "15.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "RPG",
            "Cooperativo en línea",
            "FPS",
            "Cooperación",
            "Aventura",
            "Un solo jugador",
            "Multijugador multiplataforma",
            "Multijugador",
            "RPG",
            "Action",
            "Looter Shooter",
            "Open World",
            "Loot",
            "Shooter",
            "Co-op Campaign",
            "Gore",
            "First-Person",
            "Violent",
            "Epic",
            "Nudity",
            "Comedy",
            
        ],
        "rating": "83"
    },
    {
        "title": "Jurassic World Evolution 2 Deluxe Edition",
        "image": "https://s2.gaming-cdn.com/images/products/9430/271x377/jurassic-world-evolution-2-deluxe-edition-deluxe-edition-pc-juego-steam-cover.jpg",
        "price": "42.89",
        "platform": "Steam",
        "tags": [
            "Simulación",
            "Estrategia",
            "Gestión",
            "Acción",
            "Un solo jugador",
            "Simulation",
            "Dinosaurs",
            "Building",
            "Strategy",
            "Sandbox",
            "Sci-fi",
            "City Builder",
            "Economy",
            "Resource Management",
            "Open World",
            "Violent",
            "Atmospheric",
            "Sequel",
            "Survival",
            
        ],
        "rating": "?"
    },
    {
        "title": "World War Z: Aftermath",
        "image": "https://s1.gaming-cdn.com/images/products/9078/271x377/world-war-z-aftermath-pc-juego-steam-cover.jpg",
        "price": "23.69",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperativo en línea",
            "Cooperación",
            "FPS",
            "JcJ online",
            "Multijugador",
            "Multijugador multiplataforma",
            "Un solo jugador",
            "Action",
            "Zombies",
            "Shooter",
            "Third-Person Shooter",
            "PvE",
            "Character Customization",
            "Gun Customization",
            "Post-apocalyptic",
            "First-Person",
            "Survival Horror",
            "Third Person",
            "Class-Based",
            "Violent",
            "Gore",
            "Combat",
            
        ],
        "rating": "50"
    },
    {
        "title": "Back 4 Blood Ultimate (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/8037/271x377/back-4-blood-ultimate-ultimate-edition-pc-juego-steam-europe-cover.jpg",
        "price": "87.49",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Cooperativo en línea",
            "FPS",
            "Cooperación",
            "Aventura",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Action",
            "Zombies",
            "Shooter",
            "First-Person",
            "Gore",
            "Blood",
            "Violent",
            "PvP",
            "Horror",
            "Survival",
            "Survival Horror",
            "PvE",
            "Replay Value",
            "Roguelite",
            
        ],
        "rating": "?"
    },
    {
        "title": "Hell Let Loose",
        "image": "https://s3.gaming-cdn.com/images/products/4640/271x377/juego-steam-hell-let-loose-cover.jpg",
        "price": "26.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Indies",
            "Simulación",
            "Estrategia",
            "FPS",
            "Wargame",
            "JcJ online",
            "Multijugador",
            "Massively Multiplayer",
            "Action",
            "Shooter",
            "World War II",
            "Realistic",
            "Simulation",
            "Tactical",
            "PvP",
            "First-Person",
            "Military",
            "Strategy",
            "Violent",
            "Indie",
            "Historical",
            "Gore",
            "Mature",
            "Tanks",
            
        ],
        "rating": "77"
    },
    {
        "title": "Insurgency: Sandstorm",
        "image": "https://s1.gaming-cdn.com/images/products/2160/271x377/insurgency-sandstorm-pc-juego-steam-cover.jpg",
        "price": "22.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Cooperativo en línea",
            "Cooperación",
            "FPS",
            "Indies",
            "JcJ online",
            "Multijugador",
            "Simulación",
            "Wargame",
            "Realistic",
            "Shooter",
            "Military",
            "Action",
            "Tactical",
            "First-Person",
            "Violent",
            "Gore",
            "Atmospheric",
            "Difficult",
            "Open World",
            "Massively Multiplayer",
            "Choices Matter",
            
        ],
        "rating": "80"
    },
    {
        "title": "Dark Souls 3",
        "image": "https://s3.gaming-cdn.com/images/products/857/271x377/juego-steam-dark-souls-3-cover.jpg",
        "price": "10.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperación",
            "Multijugador",
            "RPG",
            "Souls-like",
            "Dark Fantasy",
            "Difficult",
            "Atmospheric",
            "Lore-Rich",
            "Third Person",
            "Exploration",
            "Story Rich",
            "Action RPG",
            "PvP",
            "Open World",
            "Singleplayer",
            "Replay Value",
            "Character Customization",
            
        ],
        "rating": "93"
    },
    {
        "title": "Tom Clancy's Ghost Recon: Wildlands (Europe)",
        "image": "https://s3.gaming-cdn.com/images/products/878/271x377/juego-uplay-tom-clancys-ghost-recon-wildlands-cover.jpg",
        "price": "11.49",
        "platform": "Ubisoft Connect",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "FPS",
            "Multijugador",
            "Estrategia",
            "Open World",
            "Shooter",
            "Tactical",
            "Stealth",
            "Third-Person Shooter",
            "Singleplayer",
            "Military",
            "Online Co-Op",
            "Third Person",
            "Survival",
            "Sandbox",
            "First-Person",
            "Atmospheric",
            "PvP",
            
        ],
        "rating": "82"
    },
    {
        "title": "Crusader Kings III",
        "image": "https://s2.gaming-cdn.com/images/products/5692/271x377/juego-steam-crusader-kings-iii-cover.jpg",
        "price": "19.49",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "RPG",
            "Simulación",
            "Estrategia",
            "Wargame",
            "Gestión",
            "Un solo jugador",
            "JcJ online",
            "Multijugador",
            "Strategy",
            "RPG",
            "Simulation",
            "Medieval",
            "Grand Strategy",
            "Historical",
            "Political",
            "Choices Matter",
            "Sandbox",
            "Character Customization",
            "Real-Time with Pause",
            "Moddable",
            "PvP",
            "Sexual Content",
            "Nudity",
            "Dating Sim",
            
        ],
        "rating": "80"
    },
    {
        "title": "The Elder Scrolls V: Skyrim Special Edition",
        "image": "https://s1.gaming-cdn.com/images/products/1512/271x377/the-elder-scrolls-v-skyrim-special-edition-special-edition-pc-juego-steam-cover.jpg",
        "price": "15.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "RPG",
            "Open World",
            "Singleplayer",
            "Fantasy",
            "Character Customization",
            "Dragons",
            "Moddable",
            "Story Rich",
            "Magic",
            "First-Person",
            "Atmospheric",
            "Third Person",
            "Stealth",
            "Classic",
            "Remake",
            "Female Protagonist",
            "Walking Simulator",
            
        ],
        "rating": "93"
    },
    {
        "title": "Mount & Blade II: Bannerlord (Early Access)",
        "image": "https://s3.gaming-cdn.com/images/products/761/271x377/juego-steam-mount-blade-ii-bannerlord-early-access-cover.jpg",
        "price": "27.25",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "Early Access",
            "Multijugador",
            "RPG",
            "Simulación",
            "Estrategia",
            "Wargame",
            "Medieval",
            "Open World",
            "Sandbox",
            "Singleplayer",
            "Moddable",
            "Horses",
            "Character Customization",
            "Realistic",
            "Historical",
            "First-Person",
            "Third Person",
            
        ],
        "rating": "83"
    },
    {
        "title": "F1 2021",
        "image": "https://s3.gaming-cdn.com/images/products/7541/271x377/juego-steam-f1-2021-cover.jpg",
        "price": "48.99",
        "platform": "Steam",
        "tags": [
            "Carreras",
            "Multijugador",
            "Simulación",
            "Deporte",
            "Driving",
            "eSports",
            "Immersive Sim",
            "Split Screen",
            "3D",
            "Cinematic",
            "Realistic",
            "PvP",
            "Singleplayer",
            "Local Multiplayer",
            
        ],
        "rating": "69"
    },
    {
        "title": "Detroit: Become Human",
        "image": "https://s3.gaming-cdn.com/images/products/7001/271x377/juego-steam-detroit-become-human-cover.jpg",
        "price": "22.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Un solo jugador",
            "Choices Matter",
            "Story Rich",
            "Multiple Endings",
            "Cinematic",
            "Emotional",
            "Adventure",
            "Beautiful",
            "Futuristic",
            "Sci-fi",
            "Robots",
            "Dynamic Narration",
            "Third Person",
            "Atmospheric",
            "Cyberpunk",
            "Violent",
            "Replay Value",
            "Narration",
            "Female Protagonist",
            
        ],
        "rating": "92"
    },
    {
        "title": "Monster Hunter Stories 2: Wings of Ruin",
        "image": "https://s2.gaming-cdn.com/images/products/7894/271x377/juego-steam-monster-hunter-stories-2-wings-of-ruin-cover.jpg",
        "price": "28.99",
        "platform": "Steam",
        "tags": [
            "Aventura",
            "Cooperación",
            "Multijugador",
            "RPG",
            "Exploration",
            "JRPG",
            "3D",
            "Cartoony",
            "Third Person",
            "Dragons",
            "Fantasy",
            "Loot",
            "Emotional",
            "PvE",
            "PvP",
            "Character Customization",
            "Story Rich",
            "Hunting",
            "Online Co-Op",
            "Singleplayer",
            "Turn-Based",
            
        ],
        "rating": "86"
    },
    {
        "title": "Crusader Kings III Royal Edition",
        "image": "https://s3.gaming-cdn.com/images/products/7289/271x377/juego-steam-crusader-kings-iii-royal-edition-cover.jpg",
        "price": "29.89",
        "platform": "Steam",
        "tags": [
            "Multijugador",
            "RPG",
            "Simulación",
            "Estrategia",
            "Wargame",
            "Historical",
            "Grand Strategy",
            "Medieval",
            "Dating Sim",
            "Sexual Content",
            "Masterpiece",
            "Singleplayer",
            "Nudity",
            "Political",
            "Choices Matter",
            "Sandbox",
            "Female Protagonist",
            
        ],
        "rating": "80"
    },
    {
        "title": "Police Simulator: Patrol Officers (Early Access)",
        "image": "https://s3.gaming-cdn.com/images/products/9062/271x377/police-simulator-patrol-officers-early-access-pc-juego-steam-cover.jpg",
        "price": "15.99",
        "platform": "Steam",
        "tags": [
            "Beat'em all",
            "Early Access",
            "Simulación",
            "Un solo jugador",
            "Simulation",
            "Crime",
            "Open World",
            "Realistic",
            "Early Access",
            "Immersive Sim",
            "Automobile Sim",
            "Investigation",
            "Education",
            "3D",
            "Exploration",
            "Third Person",
            "Female Protagonist",
            "Survival Horror",
            "Nudity",
            "Looter Shooter",
            
        ],
        "rating": "74"
    },
    {
        "title": "Jump Force Ultimate Edition",
        "image": "https://s3.gaming-cdn.com/images/products/3899/271x377/juego-steam-jump-force-ultimate-edition-cover.jpg",
        "price": "15.20",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Lucha",
            "Cooperación",
            "Multijugador",
            "RPG",
            "Anime",
            "Character Customization",
            "Singleplayer",
            "Local Multiplayer",
            
        ],
        "rating": "68"
    },
    {
        "title": "Los Sims 4: ¡Rumbo a la Fama!",
        "image": "https://s2.gaming-cdn.com/images/products/3211/271x377/juego-origin-los-sims-4-%c2%a1rumbo-a-la-fama-cover.jpg",
        "price": "15.99",
        "platform": "Origin",
        "tags": [
            "Simulación",
            "Building",
            "Single Player",
            "Casual",
            "Character Customization",
            "Sandbox",
            "Moddable",
            "Family Friendly",
            "Romance",
            
        ],
        "rating": "90"
    },
    {
        "title": "Rogue Lords",
        "image": "https://s2.gaming-cdn.com/images/products/9508/271x377/rogue-lords-pc-juego-steam-cover.jpg",
        "price": "14.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "RPG",
            "Un solo jugador",
            "Estrategia",
            "RPG",
            "Dark Fantasy",
            "Roguelike",
            "Turn-Based Combat",
            "2D",
            "Gothic",
            "Roguelite",
            "Strategy RPG",
            "Action Roguelike",
            "Hand-drawn",
            "Stylized",
            "Mythology",
            "Vampire",
            "Supernatural",
            "Fantasy",
            "Turn-Based Strategy",
            "Strategy",
            "Cartoony",
            "Magic",
            "Dark",
            
        ],
        "rating": "?"
    },
    {
        "title": "Squad",
        "image": "https://s2.gaming-cdn.com/images/products/1309/271x377/juego-steam-squad-cover.jpg",
        "price": "27.99",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Cooperación",
            "Early Access",
            "FPS",
            "Indies",
            "Multijugador",
            "RPG",
            "Simulación",
            "Estrategia",
            "Wargame",
            "Military",
            "Realistic",
            "Tactical",
            "Shooter",
            "Team-Based",
            "First-Person",
            "Open World",
            "Massively Multiplayer",
            "Atmospheric",
            "Walking Simulator",
            "Singleplayer",
            
        ],
        "rating": "80"
    },
    {
        "title": "Ride 4",
        "image": "https://s2.gaming-cdn.com/images/products/7138/271x377/juego-steam-ride-4-cover.jpg",
        "price": "17.79",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Carreras",
            "Simulación",
            "Deporte",
            "First-Person",
            "Third Person",
            "PvP",
            "Driving",
            "Singleplayer",
            "Bikes",
            "Competitive",
            "Motorbike",
            
        ],
        "rating": "78"
    },
    {
        "title": "Transport Fever 2",
        "image": "https://s1.gaming-cdn.com/images/products/5517/271x377/juego-steam-transport-fever-2-cover.jpg",
        "price": "13.49",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Gestión",
            "Simulación",
            "Estrategia",
            "Trains",
            "Economy",
            "Singleplayer",
            "Transportation",
            
        ],
        "rating": "85"
    },
    {
        "title": "Los Sims 4: Vida Isleña",
        "image": "https://s2.gaming-cdn.com/images/products/4624/271x377/juego-origin-los-sims-4-vida-islena-cover.jpg",
        "price": "17.49",
        "platform": "Origin",
        "tags": [
            "Simulación",
            "Single Player",
            "Casual",
            "Character Customization",
            "Sandbox",
            "Moddable",
            "Family Friendly",
            
        ],
        "rating": "86"
    },
    {
        "title": "Tribes of Midgard - Deluxe Edition",
        "image": "https://s1.gaming-cdn.com/images/products/9315/271x377/juego-steam-tribes-of-midgard-deluxe-edition-cover.jpg",
        "price": "11.98",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura",
            "Cooperativo en línea",
            "Cooperación",
            "Indies",
            "RPG",
            "Un solo jugador",
            "Action",
            "Adventure",
            "Indie",
            "Survival",
            "RPG",
            "Crafting",
            "Procedural Generation",
            "Open World",
            "Tower Defense",
            "Vikings",
            "Action RPG",
            "Roguelike",
            
        ],
        "rating": "75"
    },
    {
        "title": "Sid Meier's Civilization VI Anthology",
        "image": "https://s3.gaming-cdn.com/images/products/9038/271x377/juego-steam-sid-meiers-civilization-vi-anthology-cover.jpg",
        "price": "21.99",
        "platform": "Steam",
        "tags": [
            "Cooperación",
            "Gestión",
            "Multijugador",
            "Simulación",
            "Estrategia",
            "Wargame",
            "Turn-Based Strategy",
            "Historical",
            "Singleplayer",
            "Turn-Based",
            "Grand Strategy",
            "4X",
            "Tactical",
            "City Builder",
            "Moddable",
            "Online Co-Op",
            "Building",
            "Hex Grid",
            "Atmospheric",
            
        ],
        "rating": "87"
    },
    {
        "title": "The Crew 2 Gold Edition (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/4639/271x377/juego-uplay-the-crew-2-gold-edition-cover.jpg",
        "price": "15.89",
        "platform": "Ubisoft Connect",
        "tags": [
            "Acción",
            "Arcade",
            "Aventura",
            "Cooperación",
            "Carreras",
            "Multijugador",
            "Simulación",
            "Deporte",
            "Massively Multiplayer",
            "Open World",
            "Driving",
            "Flight",
            "Singleplayer",
            "First-Person",
            "Third Person",
            "Online Co-Op",
            "Atmospheric",
            "America",
            "Sandbox",
            "Funny",
            
        ],
        "rating": "75"
    },
    {
        "title": "Biomutant",
        "image": "https://s2.gaming-cdn.com/images/products/2245/271x377/juego-steam-biomutant-cover.jpg",
        "price": "25.89",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "Indies",
            "RPG",
            "Open World",
            "Singleplayer",
            "Hack and Slash",
            "Post-apocalyptic",
            "Third Person",
            "Fantasy",
            "Atmospheric",
            "Character Customization",
            "Action RPG",
            "Exploration",
            "Sci-fi",
            "Martial Arts",
            "Cute",
            "Story Rich",
            
        ],
        "rating": "65"
    },
    {
        "title": "Total War: Warhammer",
        "image": "https://s1.gaming-cdn.com/images/products/795/271x377/juego-steam-total-war-warhammer-cover.jpg",
        "price": "11.20",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Estrategia",
            "Wargame",
            "Multijugador",
            "Cooperación",
            "RPG",
            "Fantasy",
            "RTS",
            "Turn-Based Strategy",
            "Games Workshop",
            "Grand Strategy",
            "Tactical",
            "Dark Fantasy",
            "Singleplayer",
            "Turn-Based",
            "Atmospheric",
            "Story Rich",
            "Open World",
            "Gore",
            "Warhammer 40K",
            
        ],
        "rating": "84"
    },
    {
        "title": "Mortal Kombat 11",
        "image": "https://s1.gaming-cdn.com/images/products/3339/271x377/juego-steam-mortal-kombat-11-cover.jpg",
        "price": "11.89",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Arcade",
            "Lucha",
            "Multijugador",
            "Gore",
            "Violent",
            "Blood",
            "2D Fighter",
            "Mature",
            "Competitive",
            "Character Customization",
            "Singleplayer",
            "Story Rich",
            "Local Multiplayer",
            "Atmospheric",
            "2.5D",
            "Cute",
            "Horror",
            "Sexual Content",
            
        ],
        "rating": "86"
    },
    {
        "title": "Battlefield 4: Premium Edition (juego incluido + all DLC)",
        "image": "https://s2.gaming-cdn.com/images/products/577/271x377/juego-origin-battlefield-4-premium-edition-juego-incluido-all-dlc-cover.jpg",
        "price": "10.99",
        "platform": "Origin",
        "tags": [
            "Acción",
            "FPS",
            "Multijugador",
            "Wargame",
            "Singleplayer"
        ],
        "rating": "85"
    },
    {
        "title": "Monster Hunter: World - Iceborne Master Edition",
        "image": "https://s2.gaming-cdn.com/images/products/6163/271x377/juego-steam-monster-hunter-world-iceborne-master-edition-cover.jpg",
        "price": "26.13",
        "platform": "Steam",
        "tags": [
            "Acción",
            "Aventura"
        ],
        "rating": "87"
    },
    {
        "title": "Scum (Early Access)",
        "image": "https://s3.gaming-cdn.com/images/products/2159/271x377/juego-steam-scum-early-access-cover.jpg",
        "price": "21.49",
        "platform": "Steam",
        "tags": [
            "GeForce Now",
            "Acción",
            "Aventura",
            "Cooperación",
            "Early Access",
            "FPS",
            "Indies",
            "Multijugador",
            "RPG",
            "Massively Multiplayer",
            "Survival",
            "Open World Survival Craft",
            "Open World",
            "Zombies",
            "Crafting",
            "Realistic",
            "Nudity",
            "Violent",
            "Singleplayer",
            "PvP",
            "Third Person",
            "Gore",
            
        ],
        "rating": "79"
    },
    {
        "title": "Assassin's Creed Valhalla - Season Pass (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/7831/271x377/juego-uplay-assassins-creed-valhalla-season-pass-cover.jpg",
        "price": "28.69",
        "platform": "Ubisoft Connect",
        "tags": [
            "Acción",
            "Aventura",
            "Open World",
            "Parkour",
            "Assassin",
            "Stealth",
            "Third Person",
            "Historical",
            "Singleplayer",
            "Story Rich",
            "Hunting",
            "Atmospheric",
            "Action-Adventure",
            "Sandbox",
            "Controller",
            "Casual",
            
        ],
        "rating": "95"
    },
    {
        "title": "Football Manager 2021 (Europe)",
        "image": "https://s1.gaming-cdn.com/images/products/7383/271x377/juego-steam-football-manager-2021-cover.jpg",
        "price": "19.99",
        "platform": "Steam",
        "tags": [
            "Gestión",
            "Simulación",
            "Deporte",
            "Singleplayer",
            "Football"
        ],
        "rating": "84"
    },
    {
        "title": "Borderlands 3 Ultimate Edition (Europe)",
        "image": "https://s2.gaming-cdn.com/images/products/7876/271x377/juego-steam-borderlands-3-ultimate-edition-cover.jpg",
        "price": "35.99",
        "platform": "Steam",
        "tags": [
            "Acción",
            "RPG",
            "Cooperativo en línea",
            "FPS",
            "Cooperación",
            "Aventura",
            "Un solo jugador",
            "Multijugador multiplataforma",
            "Multijugador",
            "RPG",
            "Action",
            "Looter Shooter",
            "Open World",
            "Loot",
            "Shooter",
            "Co-op Campaign",
            "Gore",
            "First-Person",
            "Violent",
            "Epic",
            "Nudity",
            "Comedy",
            
        ],
        "rating": "83"
    },
    {
        "title": "Planet Zoo: Deluxe Edition",
        "image": "https://s3.gaming-cdn.com/images/products/5762/271x377/planet-zoo-deluxe-edition-deluxe-edition-pc-juego-steam-cover.jpg",
        "price": "18.99",
        "platform": "Steam",
        "tags": [
            "Gestión",
            "Simulación",
            "Un solo jugador",
            "Estrategia",
            "Casual",
            "Simulation",
            "Building",
            "Nature",
            "Sandbox",
            "City Builder",
            "Economy",
            "Family Friendly",
            "Realistic",
            "Resource Management",
            "Cute",
            "Strategy",
            "Relaxing",
            "Open World",
            "Funny",
            "Horses",
            
        ],
        "rating": "88"
    }
]

export default data